"""ZIP packager: DXF + SVG + IFC4 + IFC2x3 + PDF + README + validation.json + params.json."""
from __future__ import annotations

import hashlib
import io
import json
import re
import time
import zipfile
from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import datetime, timezone
from typing import Optional

from .dxf_writer import build_dxf
from .geometry import EnvelopeResult
from .ifc_writer import build_ifc
from .io.validate_outputs import validate_pack
from .obc import OBCResult, check_obc
from .pdf_writer import build_pdf
from .svg_preview import generate_svg
from .typology.selector import FitResult
from .validators import build_compliance_rows, validate_all
from .zoning_resolver import resolve_zoning


_README_TEMPLATE = """\
PACKGEN OUTPUT BUNDLE
=====================
Generated: {timestamp}

FILES
  plans.dxf            AutoCAD 2018+ DXF. Open in AutoCAD: File > Open.
                       Layers follow AIA/NCS convention (A-WALL-FULL, A-DOOR, A-GLAZ, etc.)
                       Paperspace tabs: Site Plan, Ground Floor, Second Floor, Roof Plan.
  plans.svg            Browser-viewable floor plan preview.
  model_ifc4.ifc       BIM model, IFC4 schema. Open in Revit: File > Open > IFC.
  model_ifc2x3.ifc     BIM model, IFC2x3 Coordination View 2.0.
                       Use this if IFC4 fails to import in Revit.
  report.pdf           Compliance report with by-law citations and variance summary.
  params.json          Machine-readable parameters used to generate this plan.
  validation.json      Automated validation results (entity counts, layer check, schema errors).

ZONING
  By-law 569-2013 (Office Consolidation, July 31 2024)
  Zone: {zone_symbol}
  Address: {address}

DISCLAIMER
  This is a CONCEPT DOCUMENT, not a permit set. A licensed Ontario architect or
  BCIN-qualified designer must review and seal drawings before any application
  to Toronto Building. Generated by PackGen AI.

HOW TO OPEN
  AutoCAD:  File > Open > select plans.dxf > check paperspace tabs at bottom.
  Revit:    File > Open > IFC > select model_ifc4.ifc.
            If layout looks wrong, retry with model_ifc2x3.ifc.
  Report:   Open report.pdf — contains compliance audit with §-level citations.
"""


def _obc_summary(obc: OBCResult) -> dict:
    return {
        "pass": obc.pass_,
        "violations": [
            {
                "severity": v.severity,
                "code_ref": v.code_ref,
                "unit_id": v.unit_id,
                "storey": v.storey,
                "role": v.cell_role,
                "message": v.message,
            }
            for v in obc.violations
        ],
        "assumptions": obc.assumptions,
    }


def _params_hash(params: dict) -> str:
    """Return 8-char SHA-256 of the params dict (stable across calls with same values)."""
    blob = json.dumps(params, sort_keys=True, ensure_ascii=False).encode()
    return hashlib.sha256(blob).hexdigest()[:8]


def _address_slug(address: str) -> str:
    slug = re.sub(r"[^a-zA-Z0-9]+", "_", address or "").strip("_")
    return slug[:24] if slug else "unknown"


def build_pack(
    envelope_result: EnvelopeResult,
    fits: list[FitResult],
    extra_params: Optional[dict] = None,
) -> tuple[bytes, dict[str, str]]:
    """Assemble a ZIP with DXF + SVG + IFC4 + IFC2x3 + PDF per option,
    plus params.json, README.txt, and validation.json.

    Returns (zip_bytes, svg_strings) where svg_strings maps lowercase option
    letter → raw SVG string, e.g. {"a": "<svg…>", "b": "<svg…>"}.
    Also appends "zip_filename" key to the last entry of svg_strings.

    fits[0] is Option A (vertical), fits[1] (if present) is Option B (horizontal).
    """
    zone_symbol      = (extra_params or {}).get("zone_symbol", "")
    exception_number = (extra_params or {}).get("exception_number")
    address          = (extra_params or {}).get("address", "")
    brief_summary    = (extra_params or {}).get("brief_summary", "")

    # Build compliance rows for the PDF audit table (best-effort; failures are logged).
    compliance_rows: list = []
    if zone_symbol:
        try:
            lot_data = {
                "lot_frontage_m": round(envelope_result.lot_width_m, 2),
                "lot_depth_m":    round(envelope_result.lot_depth_m, 2),
                "lot_area_m2":    round(envelope_result.lot_area_m2, 1),
            }
            resolved = resolve_zoning(zone_symbol, lot_data)

            # Derive proposed values from known envelope / fit results
            envelope_coverage = (
                envelope_result.envelope_2d.area / envelope_result.lot_area_m2 * 100
                if envelope_result.lot_area_m2 > 0 else 0.0
            )
            proposed_for_audit: dict = {
                "front_yard_setback_m":      round(envelope_result.setbacks_applied.get("front", 0), 2),
                "rear_yard_setback_m":       round(envelope_result.setbacks_applied.get("rear",  0), 2),
                "side_yard_setback_left_m":  round(envelope_result.setbacks_applied.get("left",  0), 2),
                "side_yard_setback_right_m": round(envelope_result.setbacks_applied.get("right", 0), 2),
                "lot_coverage_pct_max":      round(envelope_coverage, 1),
            }
            if fits:
                fit_a = fits[0]
                fsi = round(fit_a.gfa_m2 / envelope_result.lot_area_m2, 3) if envelope_result.lot_area_m2 > 0 else 0.0
                proposed_for_audit.update({
                    "dwelling_unit_count": fit_a.typology.units_produced,
                    "fsi_max":             fsi,
                })

            val_results = validate_all(proposed_for_audit, resolved)
            compliance_rows = build_compliance_rows(resolved, proposed_for_audit, val_results)
        except Exception as _ce:
            print(f"[packager] compliance audit skipped: {_ce}")

    svg_strings: dict[str, str] = {}
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        params: dict = {
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "bylaw": "Toronto Zoning By-law 569-2013",
            "obc_edition": "2024",
            "lot": {
                "width_m":  round(envelope_result.lot_width_m, 2),
                "depth_m":  round(envelope_result.lot_depth_m, 2),
                "area_m2":  round(envelope_result.lot_area_m2, 1),
            },
            "envelope": {
                "angular_plane_applied": envelope_result.angular_plane_applied,
                "depth_limit_m":         envelope_result.depth_limit_m,
                "setbacks_m":            {k: round(v, 2) for k, v in envelope_result.setbacks_applied.items()},
                "warnings":              envelope_result.warnings,
            },
            "options": [],
        }
        if extra_params:
            params.update(extra_params)

        all_validation: dict = {}

        for fit in fits:
            obc = check_obc(fit)
            option_key = fit.option   # "A" or "B"
            key        = option_key.lower()

            # ── Parallel export (5 workers: dxf, svg, ifc4, ifc2x3, pdf) ─
            _t0 = time.perf_counter()
            with ThreadPoolExecutor(max_workers=5, thread_name_prefix="packgen_export") as _pool:
                _futures: dict = {
                    _pool.submit(
                        build_dxf, envelope_result, fit, obc, address=address
                    ): "dxf",
                    _pool.submit(
                        generate_svg, fit, envelope_result
                    ): "svg",
                    _pool.submit(
                        build_ifc, envelope_result, fit, obc,
                        zone_symbol=zone_symbol,
                        exception_number=exception_number,
                        schema="IFC4",
                    ): "ifc4",
                    _pool.submit(
                        build_ifc, envelope_result, fit, obc,
                        zone_symbol=zone_symbol,
                        exception_number=exception_number,
                        schema="IFC2X3",
                    ): "ifc2x3",
                    _pool.submit(
                        build_pdf, envelope_result, fit, obc,
                        zone_symbol=zone_symbol,
                        exception_number=exception_number,
                        brief_summary=brief_summary,
                        compliance_rows=compliance_rows,
                    ): "pdf",
                }
                _results: dict = {}
                for _fut in as_completed(_futures):
                    _fname = _futures[_fut]
                    try:
                        _results[_fname] = _fut.result()
                    except Exception as _exc:
                        _results[_fname] = None
                        params.setdefault("warnings", []).append(
                            f"{_fname.upper()} export failed (option {option_key}): {_exc}"
                        )
            print(
                f"[packager] option {option_key} parallel export done in "
                f"{time.perf_counter() - _t0:.2f}s"
            )

            # ── Validate outputs ──────────────────────────────────────────
            n_spaces = len(fit.placed_cells)
            n_storeys = len({pc.cell.storey for pc in fit.placed_cells})
            try:
                val_summary = validate_pack(
                    dxf_bytes=_results.get("dxf"),
                    ifc4_bytes=_results.get("ifc4"),
                    ifc2x3_bytes=_results.get("ifc2x3"),
                    expected_spaces=n_spaces,
                    expected_storeys=n_storeys,
                )
                all_validation[option_key] = val_summary
            except Exception as _ve:
                all_validation[option_key] = {"error": str(_ve)}

            # ── Write results into ZIP ────────────────────────────────────
            opt_prefix = f"option_{key}"

            dxf_name = None
            if _results.get("dxf"):
                dxf_name = f"{opt_prefix}/plans.dxf"
                zf.writestr(dxf_name, _results["dxf"])

            svg_name = None
            if _results.get("svg") is not None:
                svg_name = f"{opt_prefix}/plans.svg"
                _svg = _results["svg"]
                _svg_str = _svg if isinstance(_svg, str) else _svg.decode("utf-8")
                svg_strings[key] = _svg_str
                zf.writestr(svg_name, _svg_str.encode("utf-8"))

            ifc4_name = None
            if _results.get("ifc4"):
                ifc4_name = f"{opt_prefix}/model_ifc4.ifc"
                zf.writestr(ifc4_name, _results["ifc4"])

            ifc2x3_name = None
            if _results.get("ifc2x3"):
                ifc2x3_name = f"{opt_prefix}/model_ifc2x3.ifc"
                zf.writestr(ifc2x3_name, _results["ifc2x3"])

            pdf_name = None
            if _results.get("pdf"):
                pdf_name = f"{opt_prefix}/report.pdf"
                zf.writestr(pdf_name, _results["pdf"])

            # Per-option README
            readme_txt = _README_TEMPLATE.format(
                timestamp=datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
                zone_symbol=zone_symbol or "—",
                address=address or "—",
            )
            zf.writestr(f"{opt_prefix}/README.txt", readme_txt.encode("utf-8"))

            # Validation summary
            if option_key in all_validation:
                zf.writestr(
                    f"{opt_prefix}/validation.json",
                    json.dumps(all_validation[option_key], indent=2, ensure_ascii=False).encode("utf-8"),
                )

            # Params entry
            placed_rooms = []
            for pc in fit.placed_cells:
                placed_rooms.append({
                    "role":    pc.cell.role,
                    "unit_id": pc.cell.unit_id,
                    "storey":  pc.cell.storey,
                    "x0": round(pc.x0, 3), "y0": round(pc.y0, 3),
                    "x1": round(pc.x1, 3), "y1": round(pc.y1, 3),
                    "area_m2": round(pc.area_m2, 2),
                    "width_m": round(pc.width_m, 3),
                    "depth_m": round(pc.depth_m, 3),
                })

            params["options"].append({
                "option":          option_key,
                "typology_id":     fit.typology.id,
                "typology_label":  fit.typology.label,
                "units_produced":  fit.typology.units_produced,
                "stacking_axis":   fit.typology.stacking_axis,
                "requires_basement": fit.typology.requires_basement,
                "fit_frontage_m":  round(fit.fit_frontage_m, 2),
                "fit_depth_m":     round(fit.fit_depth_m, 2),
                "gfa_m2":          round(fit.gfa_m2, 1),
                "scale_x":         round(fit.scale_x, 3),
                "scale_y":         round(fit.scale_y, 3),
                "origin_x":        round(fit.origin_local_xy[0], 3),
                "origin_y":        round(fit.origin_local_xy[1], 3),
                "obc":             _obc_summary(obc),
                "placed_cells":    placed_rooms,
                "warnings":        fit.warnings,
                "dxf_file":        dxf_name,
                "svg_file":        svg_name,
                "ifc4_file":       ifc4_name,
                "ifc2x3_file":     ifc2x3_name,
                "pdf_file":        pdf_name,
            })

        # Top-level validation.json (all options)
        if all_validation:
            zf.writestr(
                "validation.json",
                json.dumps(all_validation, indent=2, ensure_ascii=False).encode("utf-8"),
            )

        zf.writestr("params.json", json.dumps(params, indent=2, ensure_ascii=False))

        # Zoning snapshot — machine-readable audit trail of every resolved parameter.
        _snapshot_data = (extra_params or {}).get("zoning_snapshot")
        if _snapshot_data:
            zf.writestr(
                "zoning_snapshot.json",
                json.dumps(_snapshot_data, indent=2, ensure_ascii=False).encode("utf-8"),
            )

    # Compute stable hash for filename
    ph = _params_hash(params)
    slug = _address_slug(address)
    svg_strings["_zip_filename"] = f"pack_{slug}_{ph}.zip"

    return buf.getvalue(), svg_strings
